name: Docker Build

on: [pull_request]

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build
        run: make docker-build
  test:
    name: Run integration tests
    env:
      GOPATH: /tmp/go
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create GOPATH
        run: mkdir -p /tmp/go
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Run services
        run: cd test/enviroment && docker-compose up -d
      - name: Test
        run: |
          cd test/enviroment/contracts && \
          npx i && \
          npm run deploy-contract && \
          npm run codegen && \
          npm run build  && \
          npx run create && \
          npx run deploy
